env:
  es2021: true
  node: true
extends: "airbnb-base"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    no-console: "off",
    import/extensions: "off",
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
    # object-curly-newline: ["error", {
    #       "ObjectExpression": { "multiline": true, "minProperties": 5 },
    #       "ObjectPattern": { "multiline": true },
    #       "ImportDeclaration": "never",
    #       "ExportDeclaration": "never"
    #   }] }
  }
